'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { prescriptionService } from '@/lib/services/prescriptions';
import { Prescription } from '@/types';

export default function PrintPrescriptionPage() {
  const params = useParams();
  const uid = params.uid as string;
  const id = params.id as string;
  const [prescription, setPrescription] = useState<Prescription | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetch = async () => {
      try {
        setLoading(true);
        const data = await prescriptionService.getById(Number(id));
        setPrescription(data);
        // Wait for render then print
        setTimeout(() => window.print(), 300);
      } catch (err) {
        console.error('Failed to fetch prescription for print:', err);
      } finally {
        setLoading(false);
      }
    };
    if (id) fetch();
  }, [id]);

  if (loading) return <div className="p-8 text-center text-slate-500">Loading prescription...</div>;
  if (!prescription) return <div className="p-8 text-center text-red-500">Prescription not found</div>;

  return (
    <div className="p-8 max-w-3xl mx-auto bg-white">
      <header className="mb-6">
        <h1 className="text-2xl font-bold">Prescription</h1>
        <p className="text-sm text-slate-500">Patient: {prescription.patient_name} ({prescription.patient_uid})</p>
        <p className="text-sm text-slate-500">Date: {prescription.prescription_date}</p>
      </header>

      <table className="w-full border-collapse text-sm">
        <thead>
          <tr className="text-left border-b">
            <th className="py-2">Medicine</th>
            <th className="py-2">Dose</th>
            <th className="py-2">Frequency</th>
            <th className="py-2">Duration</th>
            <th className="py-2">Quantity</th>
            <th className="py-2">Instruction</th>
          </tr>
        </thead>
        <tbody>
          {prescription.items.map(item => (
            <tr key={item.id} className="border-b">
              <td className="py-2">{item.drug_name}</td>
              <td className="py-2">{item.dose_name}</td>
              <td className="py-2">{item.frequency_name}</td>
              <td className="py-2">{item.duration_name}</td>
              <td className="py-2">{item.quantity_name}</td>
              <td className="py-2">{item.instruction}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <footer className="mt-8 text-sm text-slate-500">
        <p>Generated by AarogyaDesk</p>
      </footer>
    </div>
  );
}
