"""initial

Revision ID: b772ae8d893d
Revises: 
Create Date: 2026-05-24 14:47:30.899701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b772ae8d893d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'booking_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('call', 'walk-in', name='booking_type_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'walk-in'::character varying"))
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('pending', 'completed', name='appointment_status_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('appointments_clinic_id_fkey', 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'clinic_data', ['clinic_id'], ['clinic_id'])
    op.alter_column('case_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('case_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('case_templates_clinic_id_fkey', 'case_templates', type_='foreignkey')
    op.create_foreign_key(None, 'case_templates', 'clinic_data', ['clinic_id'], ['clinic_id'])
    op.alter_column('certificate_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('certificate_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('certificate_templates_clinic_id_fkey', 'certificate_templates', type_='foreignkey')
    op.create_foreign_key(None, 'certificate_templates', 'clinic_data', ['clinic_id'], ['clinic_id'])
    op.alter_column('clinic_data', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Active', 'Inactive', name='clinic_status_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'Active'::character varying"))
    op.alter_column('clinic_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('clinic_doctors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('clinic_doctors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('clinic_doctors_clinic_id_fkey', 'clinic_doctors', type_='foreignkey')
    op.create_foreign_key(None, 'clinic_doctors', 'clinic_data', ['clinic_id'], ['clinic_id'])
    op.alter_column('clinic_subscriptions', 'plan_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('1 Month', '6 Months', '1 Year', name='plan_type_enum'),
               existing_nullable=True)
    op.alter_column('clinic_subscriptions', 'payment_status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('Paid', 'Pending', 'Partial', name='sub_payment_status_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'Paid'::character varying"))
    op.alter_column('clinic_subscriptions', 'payment_method',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Cash', 'UPI', 'Cheque', name='sub_payment_method_enum'),
               existing_nullable=True)
    op.alter_column('clinic_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('clinic_subscriptions_clinic_id_fkey', 'clinic_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'clinic_subscriptions', 'clinic_data', ['clinic_id'], ['clinic_id'])
    op.alter_column('expense_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('expense_categories_clinic_id_fkey', 'expense_categories', type_='foreignkey')
    op.create_foreign_key(None, 'expense_categories', 'clinic_data', ['clinic_id'], ['clinic_id'])
    op.alter_column('expenses', 'payment_mode',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('Cash', 'UPI', 'Cheque', name='expense_payment_mode_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'Cash'::character varying"))
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('expenses_clinic_id_fkey', 'expenses', type_='foreignkey')
    op.drop_constraint('expenses_category_id_fkey', 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'expense_categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'expenses', 'clinic_data', ['clinic_id'], ['clinic_id'])
    op.alter_column('master_diagnosis', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('master_diagnosis_clinic_id_fkey', 'master_diagnosis', type_='foreignkey')
    op.create_foreign_key(None, 'master_diagnosis', 'clinic_data', ['clinic_id'], ['clinic_id'])
    op.alter_column('master_dose', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_master_dose_clinic_id', table_name='master_dose')
    op.create_foreign_key(None, 'master_dose', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
    op.alter_column('master_duration', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_master_duration_clinic_id', table_name='master_duration')
    op.create_foreign_key(None, 'master_duration', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
    op.alter_column('master_frequency', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_master_frequency_clinic_id', table_name='master_frequency')
    op.create_foreign_key(None, 'master_frequency', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
    op.alter_column('master_medicine', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_master_medicine_clinic_id', table_name='master_medicine')
    op.create_foreign_key(None, 'master_medicine', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
    op.alter_column('master_notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_master_notes_clinic_id', table_name='master_notes')
    op.create_foreign_key(None, 'master_notes', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
    op.alter_column('master_quantity', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_master_quantity_clinic_id', table_name='master_quantity')
    op.create_foreign_key(None, 'master_quantity', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
    op.alter_column('master_treatment_option', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('master_treatment_option_clinic_id_fkey', 'master_treatment_option', type_='foreignkey')
    op.create_foreign_key(None, 'master_treatment_option', 'clinic_data', ['clinic_id'], ['clinic_id'])
    op.alter_column('medicine', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('medicine_clinic_id_fkey', 'medicine', type_='foreignkey')
    op.create_foreign_key(None, 'medicine', 'clinic_data', ['clinic_id'], ['clinic_id'])
    op.alter_column('patient_treatments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('patient_treatments_treatment_id_fkey', 'patient_treatments', type_='foreignkey')
    op.drop_constraint('patient_treatments_clinic_id_fkey', 'patient_treatments', type_='foreignkey')
    op.drop_constraint('patient_treatments_diagnosis_id_fkey', 'patient_treatments', type_='foreignkey')
    op.create_foreign_key(None, 'patient_treatments', 'clinic_data', ['clinic_id'], ['clinic_id'])
    op.create_foreign_key(None, 'patient_treatments', 'treatment_plan', ['treatment_id'], ['id'])
    op.create_foreign_key(None, 'patient_treatments', 'treatment_plan', ['diagnosis_id'], ['id'])
    op.alter_column('patient_work_done', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('patient_work_done_clinic_id_fkey', 'patient_work_done', type_='foreignkey')
    op.drop_constraint('patient_work_done_work_done_id_fkey', 'patient_work_done', type_='foreignkey')
    op.create_foreign_key(None, 'patient_work_done', 'clinic_data', ['clinic_id'], ['clinic_id'])
    op.create_foreign_key(None, 'patient_work_done', 'work_done', ['work_done_id'], ['id'])
    op.alter_column('patients', 'payment_status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('paid', 'partial', 'pending', name='payment_status_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_patients_patient_uid'), 'patients', ['patient_uid'], unique=False)
    op.drop_constraint('patients_clinic_id_fkey', 'patients', type_='foreignkey')
    op.create_foreign_key(None, 'patients', 'clinic_data', ['clinic_id'], ['clinic_id'])
    op.alter_column('prescription_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('prescription_items_clinic_id_fkey', 'prescription_items', type_='foreignkey')
    op.drop_constraint('prescription_items_frequency_id_fkey', 'prescription_items', type_='foreignkey')
    op.drop_constraint('prescription_items_quantity_id_fkey', 'prescription_items', type_='foreignkey')
    op.drop_constraint('prescription_items_drug_id_fkey', 'prescription_items', type_='foreignkey')
    op.drop_constraint('prescription_items_prescription_id_fkey', 'prescription_items', type_='foreignkey')
    op.drop_constraint('prescription_items_duration_id_fkey', 'prescription_items', type_='foreignkey')
    op.drop_constraint('prescription_items_dose_id_fkey', 'prescription_items', type_='foreignkey')
    op.create_foreign_key(None, 'prescription_items', 'master_frequency', ['frequency_id'], ['id'])
    op.create_foreign_key(None, 'prescription_items', 'clinic_data', ['clinic_id'], ['clinic_id'])
    op.create_foreign_key(None, 'prescription_items', 'prescriptions', ['prescription_id'], ['id'])
    op.create_foreign_key(None, 'prescription_items', 'master_quantity', ['quantity_id'], ['id'])
    op.create_foreign_key(None, 'prescription_items', 'master_duration', ['duration_id'], ['id'])
    op.create_foreign_key(None, 'prescription_items', 'master_dose', ['dose_id'], ['id'])
    op.create_foreign_key(None, 'prescription_items', 'master_medicine', ['drug_id'], ['id'])
    op.alter_column('prescriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('prescriptions_clinic_id_fkey', 'prescriptions', type_='foreignkey')
    op.create_foreign_key(None, 'prescriptions', 'clinic_data', ['clinic_id'], ['clinic_id'])
    op.alter_column('treatment_plan', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('treatment_plan_clinic_id_fkey', 'treatment_plan', type_='foreignkey')
    op.create_foreign_key(None, 'treatment_plan', 'clinic_data', ['clinic_id'], ['clinic_id'])
    op.alter_column('user_query', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('user_query_clinic_id_fkey', 'user_query', type_='foreignkey')
    op.create_foreign_key(None, 'user_query', 'clinic_data', ['clinic_id'], ['clinic_id'])
    op.alter_column('users', 'user_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('admin', 'clinic', name='user_type_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'clinic'::character varying"))
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('Active', 'Inactive', name='user_status_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'Active'::character varying"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint('users_clinic_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'clinic_data', ['clinic_id'], ['clinic_id'])
    op.alter_column('work_done', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('work_done_clinic_id_fkey', 'work_done', type_='foreignkey')
    op.create_foreign_key(None, 'work_done', 'clinic_data', ['clinic_id'], ['clinic_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_done', type_='foreignkey')
    op.create_foreign_key('work_done_clinic_id_fkey', 'work_done', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
    op.alter_column('work_done', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_clinic_id_fkey', 'users', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'status',
               existing_type=sa.Enum('Active', 'Inactive', name='user_status_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'Active'::character varying"))
    op.alter_column('users', 'user_type',
               existing_type=sa.Enum('admin', 'clinic', name='user_type_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'clinic'::character varying"))
    op.drop_constraint(None, 'user_query', type_='foreignkey')
    op.create_foreign_key('user_query_clinic_id_fkey', 'user_query', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
    op.alter_column('user_query', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'treatment_plan', type_='foreignkey')
    op.create_foreign_key('treatment_plan_clinic_id_fkey', 'treatment_plan', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
    op.alter_column('treatment_plan', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.create_foreign_key('prescriptions_clinic_id_fkey', 'prescriptions', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
    op.alter_column('prescriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'prescription_items', type_='foreignkey')
    op.drop_constraint(None, 'prescription_items', type_='foreignkey')
    op.drop_constraint(None, 'prescription_items', type_='foreignkey')
    op.drop_constraint(None, 'prescription_items', type_='foreignkey')
    op.drop_constraint(None, 'prescription_items', type_='foreignkey')
    op.drop_constraint(None, 'prescription_items', type_='foreignkey')
    op.drop_constraint(None, 'prescription_items', type_='foreignkey')
    op.create_foreign_key('prescription_items_dose_id_fkey', 'prescription_items', 'master_dose', ['dose_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('prescription_items_duration_id_fkey', 'prescription_items', 'master_duration', ['duration_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('prescription_items_prescription_id_fkey', 'prescription_items', 'prescriptions', ['prescription_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('prescription_items_drug_id_fkey', 'prescription_items', 'master_medicine', ['drug_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('prescription_items_quantity_id_fkey', 'prescription_items', 'master_quantity', ['quantity_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('prescription_items_frequency_id_fkey', 'prescription_items', 'master_frequency', ['frequency_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('prescription_items_clinic_id_fkey', 'prescription_items', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
    op.alter_column('prescription_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.create_foreign_key('patients_clinic_id_fkey', 'patients', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_patients_patient_uid'), table_name='patients')
    op.alter_column('patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('patients', 'payment_status',
               existing_type=sa.Enum('paid', 'partial', 'pending', name='payment_status_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_constraint(None, 'patient_work_done', type_='foreignkey')
    op.drop_constraint(None, 'patient_work_done', type_='foreignkey')
    op.create_foreign_key('patient_work_done_work_done_id_fkey', 'patient_work_done', 'work_done', ['work_done_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('patient_work_done_clinic_id_fkey', 'patient_work_done', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
    op.alter_column('patient_work_done', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'patient_treatments', type_='foreignkey')
    op.drop_constraint(None, 'patient_treatments', type_='foreignkey')
    op.drop_constraint(None, 'patient_treatments', type_='foreignkey')
    op.create_foreign_key('patient_treatments_diagnosis_id_fkey', 'patient_treatments', 'treatment_plan', ['diagnosis_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('patient_treatments_clinic_id_fkey', 'patient_treatments', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
    op.create_foreign_key('patient_treatments_treatment_id_fkey', 'patient_treatments', 'treatment_plan', ['treatment_id'], ['id'], ondelete='SET NULL')
    op.alter_column('patient_treatments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'medicine', type_='foreignkey')
    op.create_foreign_key('medicine_clinic_id_fkey', 'medicine', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
    op.alter_column('medicine', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'master_treatment_option', type_='foreignkey')
    op.create_foreign_key('master_treatment_option_clinic_id_fkey', 'master_treatment_option', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
    op.alter_column('master_treatment_option', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'master_quantity', type_='foreignkey')
    op.create_index('idx_master_quantity_clinic_id', 'master_quantity', ['clinic_id'], unique=False)
    op.alter_column('master_quantity', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'master_notes', type_='foreignkey')
    op.create_index('idx_master_notes_clinic_id', 'master_notes', ['clinic_id'], unique=False)
    op.alter_column('master_notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'master_medicine', type_='foreignkey')
    op.create_index('idx_master_medicine_clinic_id', 'master_medicine', ['clinic_id'], unique=False)
    op.alter_column('master_medicine', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'master_frequency', type_='foreignkey')
    op.create_index('idx_master_frequency_clinic_id', 'master_frequency', ['clinic_id'], unique=False)
    op.alter_column('master_frequency', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'master_duration', type_='foreignkey')
    op.create_index('idx_master_duration_clinic_id', 'master_duration', ['clinic_id'], unique=False)
    op.alter_column('master_duration', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'master_dose', type_='foreignkey')
    op.create_index('idx_master_dose_clinic_id', 'master_dose', ['clinic_id'], unique=False)
    op.alter_column('master_dose', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'master_diagnosis', type_='foreignkey')
    op.create_foreign_key('master_diagnosis_clinic_id_fkey', 'master_diagnosis', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
    op.alter_column('master_diagnosis', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key('expenses_category_id_fkey', 'expenses', 'expense_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('expenses_clinic_id_fkey', 'expenses', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('expenses', 'payment_mode',
               existing_type=sa.Enum('Cash', 'UPI', 'Cheque', name='expense_payment_mode_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'Cash'::character varying"))
    op.drop_constraint(None, 'expense_categories', type_='foreignkey')
    op.create_foreign_key('expense_categories_clinic_id_fkey', 'expense_categories', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
    op.alter_column('expense_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'clinic_subscriptions', type_='foreignkey')
    op.create_foreign_key('clinic_subscriptions_clinic_id_fkey', 'clinic_subscriptions', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
    op.alter_column('clinic_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('clinic_subscriptions', 'payment_method',
               existing_type=sa.Enum('Cash', 'UPI', 'Cheque', name='sub_payment_method_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('clinic_subscriptions', 'payment_status',
               existing_type=sa.Enum('Paid', 'Pending', 'Partial', name='sub_payment_status_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'Paid'::character varying"))
    op.alter_column('clinic_subscriptions', 'plan_type',
               existing_type=sa.Enum('1 Month', '6 Months', '1 Year', name='plan_type_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_constraint(None, 'clinic_doctors', type_='foreignkey')
    op.create_foreign_key('clinic_doctors_clinic_id_fkey', 'clinic_doctors', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
    op.alter_column('clinic_doctors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('clinic_doctors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('clinic_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('clinic_data', 'status',
               existing_type=sa.Enum('Active', 'Inactive', name='clinic_status_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'Active'::character varying"))
    op.drop_constraint(None, 'certificate_templates', type_='foreignkey')
    op.create_foreign_key('certificate_templates_clinic_id_fkey', 'certificate_templates', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
    op.alter_column('certificate_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('certificate_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'case_templates', type_='foreignkey')
    op.create_foreign_key('case_templates_clinic_id_fkey', 'case_templates', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
    op.alter_column('case_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('case_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key('appointments_clinic_id_fkey', 'appointments', 'clinic_data', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('appointments', 'status',
               existing_type=sa.Enum('pending', 'completed', name='appointment_status_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('appointments', 'booking_type',
               existing_type=sa.Enum('call', 'walk-in', name='booking_type_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'walk-in'::character varying"))
    # ### end Alembic commands ###
